version: "3"

services:
  web:
    build: . # se tim den file Dockerfile
    container_name: intern-web
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8299:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: intern-db
    restart: always
    environment:
      POSTGRES_PASSWORD: '10101997'
      POSTGRES_DB: '9gag'
    ports:
      - "5432:5432"

  jenkins:
    build: ./jenkins
    container_name: intern-jenkins
    restart: always
    ports:
      - "8298:8080"
      - "8297:5000"
      - "8296:50000"